chore(tests): add separate npm test target for unit and e2e test calls
redhat-developer/podman-desktop-redhat-account-ext pull request #110
Opened 2024-04-16 15:31 UTC by odockal

Fixes #109.

To test this you can run:
`yarn test` -> runs all unit and e2e tests, creates junit files if env. var. CI=true is set at `test-resources` and `tests/output`.
`yarn test:uni` -> runs unit tests only
`yarn test:e2e` -> run e2e tests only

2024-04-17 05:44 UTC, dgolovin commented
@odockal I can run unit or e2e tests and both, but e2e fails for me with error

![image](https://github.com/redhat-developer/podman-desktop-redhat-account-ext/assets/620330/44612853-dff2-4bdc-9709-10f38b1dcabb)

2024-04-17 06:58 UTC, odockal commented
@dgolovin I am sorry, I forgot to add steps necessary to run e2e tests actually. See the updated description.

2024-04-18 06:06 UTC, dgolovin commented
Running form console on my mac and I get this

```
eskimo@degolovi-mac accounts % PODMAN_DESKTOP_ARGS=~/Sources/podman-desktop yarn test:e2e
yarn run v1.22.19
warning package.json: "dependencies" has dependency "@types/node" with range "^18.15.11" that collides with a dependency in "devDependencies" of the same name with version "^20"
warning redhat-authentication@0.0.2: The engine "podman-desktop" appears to be invalid.
$ npm run test:e2e:setup vitest run tests/src/ --pool=threads --poolOptions.threads.singleThread --poolOptions.threads.isolate --no-file-parallelism

> redhat-authentication@0.0.2 test:e2e:setup
> xvfb-maybe --auto-servernum --server-args='-screen 0 1280x960x24' -- vitest run tests/src/

sh: xvfb-maybe: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
eskimo@degolovi-mac accounts % 
```

2024-04-18 12:15 UTC, odockal commented
> Running form console on my mac and I get this
> 
> ```
> eskimo@degolovi-mac accounts % PODMAN_DESKTOP_ARGS=~/Sources/podman-desktop yarn test:e2e
> yarn run v1.22.19
> warning package.json: "dependencies" has dependency "@types/node" with range "^18.15.11" that collides with a dependency in "devDependencies" of the same name with version "^20"
> warning redhat-authentication@0.0.2: The engine "podman-desktop" appears to be invalid.
> $ npm run test:e2e:setup vitest run tests/src/ --pool=threads --poolOptions.threads.singleThread --poolOptions.threads.isolate --no-file-parallelism
> 
> > redhat-authentication@0.0.2 test:e2e:setup
> > xvfb-maybe --auto-servernum --server-args='-screen 0 1280x960x24' -- vitest run tests/src/
> 
> sh: xvfb-maybe: command not found
> error Command failed with exit code 127.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> eskimo@degolovi-mac accounts % 
> ```

Did you run `yarn install` before?

2024-04-18 16:56 UTC, dgolovin requested changes
I would rather keep `yarn test` behavior and introduce `test:all` or `test:ci` that run all the tests in CI.

2024-04-18 16:56 UTC, dgolovin commented on package.json
> +    "test": "npm run test:unit && npm run test:e2e",
```suggestion
    "test:all": "npm run test:unit && npm run test:e2e",
```

2024-04-18 16:56 UTC, dgolovin commented on package.json
> +    "test:unit": "vitest run --coverage",
```suggestion
    "test": "vitest run --coverage",
```

2024-04-18 18:56 UTC, odockal commented
@dgolovin No problem. Done. ATM I do not see a reason to distinguish between tests on ci or locally via npm script targets.

2024-04-18 19:14 UTC, dgolovin approved these changes

2024-04-18 21:25 UTC, merged