fix: improve rollup build time
redhat-developer/podman-desktop-redhat-account-ext pull request #147
Opened 2024-05-28 23:41 UTC by dgolovin

fix #65.

Switching to vite for build leads to the error below

```
Error: Algorithm "sha256"  not supported. supported values: sha1, md5, passthrough
console.<computed> @ VM5:2
(anonymous) @ VM5:2
emit @ VM4 sandbox_bundle:2
onMessage @ VM4 sandbox_bundle:2
```

It seems vite always assumes the app is going to be running in browser and embeds polyfill for 'crypto' package which supports only digests listed in the message above.

Rollup works fine, except the build.js script is very slow because it packages node_modules folder into .cdix archive.
This PR addresses it buy using .extfiles that specifies what to package. The result is a build that works much faster - 3 vs 300 seconds.

2024-05-29 13:22 UTC, odockal requested changes

2024-05-29 13:22 UTC, odockal commented on .extfiles
> +ww/**
you meant "www" folder perhaps?

2024-05-29 13:22 UTC, odockal commented on scripts/build.js
> + * Copyright (C) 2023 Red Hat, Inc.
2022 - 2024?

2024-05-29 13:22 UTC, odockal commented on rollup.config.js
> +import {builtinModules} from 'module';
formatting might complain about missing spaces in the imported function.

2024-05-29 14:00 UTC, benoitf commented
I'm still wondering why we can't use vite we were able to switch all podman desktop extensions to vite

2024-05-29 14:01 UTC, benoitf commented
you're specifying build.target to be node ?

2024-05-31 07:31 UTC, jeffmaury reviewed
Also PR is mixing 2 concerns

2024-05-31 07:31 UTC, jeffmaury commented on package.json
> +    "format:check": "prettier --end-of-line auto --cache --check \"{src,types,scripts,.}/**/*.{ts,js}\"",
if . is added the others should be removed for better readability

2024-05-31 17:13 UTC, dgolovin commented
@benoitf I figured out why digest is missing, tried different solutions. Making module 'object-hash' external works. See explanation in commit comment.

2024-05-31 18:08 UTC, benoitf commented
awesome 😎

2024-05-31 18:08 UTC, benoitf approved these changes

2024-05-31 21:19 UTC, merged